//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_4_11.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public long MaDH { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public long MaKH { get; set; }
        public string TongTien { get; set; }
    }
}
