//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_4_11.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSX
    {
        public long MaNSX { get; set; }
        public string TenNSX { get; set; }
        public int SoLuongNhap { get; set; }
        public string DiaChiNSX { get; set; }
    }
}
